# Generated by Django 3.0.4 on 2020-04-21 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
