# Generated by Django 3.0.4 on 2020-04-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0002_auto_20200421_0318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealorder',
            name='mealstooerder',
        ),
    ]
