# Generated by Django 3.0.4 on 2020-04-21 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0003_remove_mealorder_mealstooerder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crm_food_app.Order', verbose_name='order'),
        ),
    ]
