# Generated by Django 3.0.4 on 2020-04-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0004_auto_20200421_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkorder',
            name='ordername',
            field=models.CharField(default=True, max_length=150),
        ),
    ]
