# Generated by Django 3.0.4 on 2020-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0005_checkorder_ordername'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkedmeal',
            name='title',
            field=models.CharField(default='', max_length=150),
        ),
    ]
