# Generated by Django 3.0.4 on 2020-04-27 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0008_auto_20200423_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedmeal',
            name='check_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_fk', to='crm_food_app.CheckOrder', verbose_name='checkfk'),
        ),
        migrations.AlterField(
            model_name='checkedmeal',
            name='mealorder',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='crm_food_app.MealOrder'),
        ),
    ]
