# Generated by Django 3.0.4 on 2020-04-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0009_auto_20200427_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedmeal',
            name='mealorder',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crm_food_app.MealOrder'),
        ),
    ]
