# Generated by Django 3.0.4 on 2020-04-27 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0011_auto_20200427_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedmeal',
            name='check_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_fk', to='crm_food_app.CheckOrder', verbose_name='checkfk'),
        ),
    ]
