# Generated by Django 3.0.4 on 2020-05-02 05:57

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_food_app', '0016_auto_20200429_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('surname', models.CharField(max_length=255)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=255)),
                ('role', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crm_food_app.Role')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(models.Model, django.contrib.auth.models.AnonymousUser),
        ),
        migrations.AlterField(
            model_name='order',
            name='waiter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='crm_food_app.User'),
        ),
    ]
